-- GolfCoach Pro: esquema PostgreSQL genérico para seguimiento de golfistas.
-- No depende de extensiones, autenticación ni políticas específicas de Supabase.
-- Los identificadores usan snake_case en minúsculas para facilitar su uso desde ORMs.

BEGIN;

CREATE TABLE players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    email text UNIQUE,
    phone text,
    birth_date date,
    nationality text,
    current_handicap numeric(4, 1),
    target_handicap numeric(4, 1),
    home_club text,
    federation_license text,
    dominant_hand text NOT NULL DEFAULT 'right',
    experience_years smallint,
    driver_distance_avg_meters numeric(5, 1),
    player_category text,
    is_active boolean NOT NULL DEFAULT true,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT players_full_name_not_blank CHECK (btrim(full_name) <> ''),
    CONSTRAINT players_email_format CHECK (
        email IS NULL OR position('@' IN email) > 1
    ),
    CONSTRAINT players_current_handicap_range CHECK (
        current_handicap IS NULL OR current_handicap BETWEEN -10.0 AND 54.0
    ),
    CONSTRAINT players_target_handicap_range CHECK (
        target_handicap IS NULL OR target_handicap BETWEEN -10.0 AND 54.0
    ),
    CONSTRAINT players_dominant_hand_check CHECK (
        dominant_hand IN ('right', 'left', 'ambidextrous')
    ),
    CONSTRAINT players_experience_years_check CHECK (
        experience_years IS NULL OR experience_years BETWEEN 0 AND 100
    ),
    CONSTRAINT players_driver_distance_check CHECK (
        driver_distance_avg_meters IS NULL OR driver_distance_avg_meters BETWEEN 0 AND 500
    )
);

COMMENT ON TABLE players IS
    'Ficha principal de cada golfista que trabaja con el entrenador.';
COMMENT ON COLUMN players.full_name IS
    'Nombre completo mostrado en la ficha de la interfaz; no se divide obligatoriamente en nombre y apellido.';
COMMENT ON COLUMN players.current_handicap IS
    'Hándicap actual mostrado en la ficha. La aplicación debe mantenerlo alineado con el registro vigente del historial.';
COMMENT ON COLUMN players.target_handicap IS
    'Hándicap objetivo definido para el plan de entrenamiento del golfista.';
COMMENT ON COLUMN players.dominant_hand IS
    'Lado de juego: right, left o ambidextrous.';
COMMENT ON COLUMN players.is_active IS
    'Permite conservar el historial de un golfista que ya no está activo.';

CREATE INDEX players_full_name_idx
    ON players (full_name);


CREATE TABLE handicap_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    handicap_index numeric(4, 1) NOT NULL,
    effective_date date NOT NULL,
    source text NOT NULL DEFAULT 'manual',
    is_current boolean NOT NULL DEFAULT false,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT handicap_history_index_range CHECK (
        handicap_index >= -10.0 AND handicap_index <= 54.0
    ),
    CONSTRAINT handicap_history_source_check CHECK (
        source IN ('manual', 'federation', 'imported', 'other')
    )
);

COMMENT ON TABLE handicap_history IS
    'Evolución del índice de hándicap de cada golfista a lo largo del tiempo.';
COMMENT ON COLUMN handicap_history.is_current IS
    'Debe marcarse en una sola fila por jugador cuando se quiera identificar el hándicap vigente.';

-- Permite varios registros del mismo día y ordena el historial de cada golfista.
CREATE INDEX handicap_history_player_effective_date_idx
    ON handicap_history (player_id, effective_date DESC, created_at DESC);

-- La restricción parcial evita más de un hándicap vigente por golfista y acelera su consulta.
CREATE UNIQUE INDEX handicap_history_one_current_per_player_idx
    ON handicap_history (player_id)
    WHERE is_current;


CREATE TABLE tournaments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    name text NOT NULL,
    organizer text,
    course_name text,
    city text,
    country text,
    start_date date NOT NULL,
    end_date date NOT NULL,
    competition_format text NOT NULL DEFAULT 'stroke_play',
    status text NOT NULL DEFAULT 'scheduled',
    final_position smallint,
    total_score smallint,
    course_par smallint,
    course_rating numeric(4, 1),
    slope_rating smallint,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tournaments_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT tournaments_dates_check CHECK (end_date >= start_date),
    CONSTRAINT tournaments_format_check CHECK (
        competition_format IN ('stroke_play', 'match_play', 'stableford', 'scramble', 'other')
    ),
    CONSTRAINT tournaments_status_check CHECK (
        status IN ('scheduled', 'in_progress', 'completed', 'cancelled')
    ),
    CONSTRAINT tournaments_final_position_check CHECK (
        final_position IS NULL OR final_position > 0
    ),
    CONSTRAINT tournaments_total_score_check CHECK (
        total_score IS NULL OR total_score BETWEEN 1 AND 360
    ),
    CONSTRAINT tournaments_course_par_check CHECK (
        course_par IS NULL OR course_par BETWEEN 54 AND 90
    ),
    CONSTRAINT tournaments_course_rating_check CHECK (
        course_rating IS NULL OR course_rating BETWEEN 45.0 AND 85.0
    ),
    CONSTRAINT tournaments_slope_rating_check CHECK (
        slope_rating IS NULL OR slope_rating BETWEEN 55 AND 155
    )
);

COMMENT ON TABLE tournaments IS
    'Torneos o competiciones registrados para un golfista concreto en el MVP.';
COMMENT ON COLUMN tournaments.player_id IS
    'Golfista al que pertenece el registro del torneo en el flujo MVP.';
COMMENT ON COLUMN tournaments.course_name IS
    'Nombre del campo o club donde se disputa el torneo.';
COMMENT ON COLUMN tournaments.competition_format IS
    'Modalidad de juego del torneo; se mantiene como texto validado para ser portable.';

-- Cubre la clave foránea y el historial de torneos que muestra la ficha del golfista.
CREATE INDEX tournaments_player_start_date_idx
    ON tournaments (player_id, start_date DESC);

CREATE INDEX tournaments_start_date_idx
    ON tournaments (start_date);


CREATE TABLE rounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    tournament_id bigint REFERENCES tournaments(id) ON DELETE SET NULL,
    round_number smallint NOT NULL DEFAULT 1,
    played_on date NOT NULL,
    course_name text NOT NULL,
    tee_name text,
    status text NOT NULL DEFAULT 'completed',
    holes_played smallint NOT NULL DEFAULT 18,
    course_par smallint,
    course_rating numeric(4, 1),
    slope_rating smallint,
    gross_score smallint,
    net_score smallint,
    score_to_par smallint,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rounds_round_number_check CHECK (round_number > 0),
    CONSTRAINT rounds_course_name_not_blank CHECK (btrim(course_name) <> ''),
    CONSTRAINT rounds_status_check CHECK (
        status IN ('in_progress', 'completed', 'withdrawn', 'cancelled')
    ),
    CONSTRAINT rounds_holes_played_check CHECK (holes_played BETWEEN 1 AND 18),
    CONSTRAINT rounds_course_par_check CHECK (
        course_par IS NULL OR course_par BETWEEN 54 AND 90
    ),
    CONSTRAINT rounds_course_rating_check CHECK (
        course_rating IS NULL OR course_rating BETWEEN 45.0 AND 85.0
    ),
    CONSTRAINT rounds_slope_rating_check CHECK (
        slope_rating IS NULL OR slope_rating BETWEEN 55 AND 155
    ),
    CONSTRAINT rounds_gross_score_check CHECK (
        gross_score IS NULL OR gross_score BETWEEN holes_played AND holes_played * 20
    ),
    CONSTRAINT rounds_net_score_check CHECK (
        net_score IS NULL OR net_score BETWEEN 0 AND holes_played * 20
    ),
    CONSTRAINT rounds_score_to_par_check CHECK (
        score_to_par IS NULL OR score_to_par BETWEEN -72 AND 72
    )
);

COMMENT ON TABLE rounds IS
    'Una vuelta jugada por un golfista, sea de torneo, práctica o juego casual.';
COMMENT ON COLUMN rounds.tournament_id IS
    'Es opcional para permitir registrar vueltas que no pertenecen a un torneo.';
COMMENT ON COLUMN rounds.gross_score IS
    'Resultado bruto total; puede contrastarse con la suma de round_holes.';

-- Un golfista solo puede tener una vuelta numerada por torneo.
CREATE UNIQUE INDEX rounds_player_tournament_round_number_idx
    ON rounds (player_id, tournament_id, round_number)
    WHERE tournament_id IS NOT NULL;

-- Cubre las consultas habituales del historial de vueltas por jugador y fecha.
CREATE INDEX rounds_player_played_on_idx
    ON rounds (player_id, played_on DESC);

-- Índice de la clave foránea tournament_id para listados y borrados del torneo.
CREATE INDEX rounds_tournament_round_number_idx
    ON rounds (tournament_id, round_number)
    WHERE tournament_id IS NOT NULL;


CREATE TABLE round_holes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id bigint NOT NULL REFERENCES rounds(id) ON DELETE CASCADE,
    hole_number smallint NOT NULL,
    par smallint NOT NULL,
    strokes smallint NOT NULL,
    putts smallint,
    penalty_strokes smallint NOT NULL DEFAULT 0,
    fairway_hit boolean,
    green_in_regulation boolean,
    sand_shots smallint NOT NULL DEFAULT 0,
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT round_holes_hole_number_check CHECK (hole_number BETWEEN 1 AND 18),
    CONSTRAINT round_holes_par_check CHECK (par BETWEEN 3 AND 6),
    CONSTRAINT round_holes_strokes_check CHECK (strokes BETWEEN 1 AND 20),
    CONSTRAINT round_holes_putts_check CHECK (
        putts IS NULL OR putts BETWEEN 0 AND strokes
    ),
    CONSTRAINT round_holes_penalty_strokes_check CHECK (
        penalty_strokes BETWEEN 0 AND strokes
    ),
    CONSTRAINT round_holes_sand_shots_check CHECK (
        sand_shots BETWEEN 0 AND strokes
    ),
    CONSTRAINT round_holes_round_hole_number_key UNIQUE (round_id, hole_number)
);

COMMENT ON TABLE round_holes IS
    'Resultado y estadísticas de cada hoyo jugado dentro de una vuelta.';
COMMENT ON COLUMN round_holes.fairway_hit IS
    'Puede quedar nulo cuando la métrica no aplique, por ejemplo en un par 3.';
COMMENT ON COLUMN round_holes.green_in_regulation IS
    'Indica si el green se alcanzó en regulación (GIR).';

-- La restricción UNIQUE anterior también crea el índice necesario para round_id.


CREATE TABLE shot_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_hole_id bigint NOT NULL REFERENCES round_holes(id) ON DELETE CASCADE,
    shot_number smallint NOT NULL,
    shot_type text NOT NULL,
    club text,
    lie_before text,
    distance_to_hole_before_meters numeric(6, 1),
    shot_distance_meters numeric(6, 1),
    result text NOT NULL DEFAULT 'in_play',
    is_penalty boolean NOT NULL DEFAULT false,
    strokes_gained numeric(6, 3),
    notes text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT shot_logs_shot_number_check CHECK (shot_number BETWEEN 1 AND 30),
    CONSTRAINT shot_logs_type_check CHECK (
        shot_type IN ('tee', 'approach', 'layup', 'recovery', 'chip', 'pitch', 'bunker', 'putt', 'penalty', 'other')
    ),
    CONSTRAINT shot_logs_lie_before_check CHECK (
        lie_before IS NULL OR lie_before IN (
            'tee', 'fairway', 'rough', 'bunker', 'green', 'penalty_area', 'recovery', 'other'
        )
    ),
    CONSTRAINT shot_logs_distance_to_hole_check CHECK (
        distance_to_hole_before_meters IS NULL OR distance_to_hole_before_meters >= 0
    ),
    CONSTRAINT shot_logs_shot_distance_check CHECK (
        shot_distance_meters IS NULL OR shot_distance_meters >= 0
    ),
    CONSTRAINT shot_logs_result_check CHECK (
        result IN ('in_play', 'hole_out', 'penalty', 'out_of_bounds', 'water', 'lost_ball', 'other')
    ),
    CONSTRAINT shot_logs_hole_shot_number_key UNIQUE (round_hole_id, shot_number)
);

COMMENT ON TABLE shot_logs IS
    'Registro opcional y granular de cada golpe; una vuelta puede no tener estos datos.';
COMMENT ON COLUMN shot_logs.strokes_gained IS
    'Métrica opcional de golpes ganados, calculada por la aplicación o un proceso analítico.';
COMMENT ON COLUMN shot_logs.round_hole_id IS
    'Relaciona el golpe con un hoyo concreto y, de forma indirecta, con su vuelta y golfista.';

-- La restricción UNIQUE anterior también crea el índice necesario para round_hole_id.

COMMIT;
